version: '3'

services:
  laravel:
    image: orchisltd/laravel:10
    ports:
      - '${APP_PORT:-0}:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
      - redis

  node:
    image: node:16
    ports:
      - '${HOST_VITE_PORT:-0}:5173'
    command: ["bash", "-c", "npm install && npm run dev"]
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

  mariadb:
    image: mariadb
    ports:
      - '${HOST_MARIADB_PORT:-0}:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '${HOST_PHP_MY_ADMIN_PORT:-0}:80'
    environment:
      PMA_HOST: mariadb
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'

  redis:
    image: 'redis:alpine'
    ports:
      - '${HOST_REDIS_PORT:-0}:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${HOST_MAILHOG_PORT:-0}:1025'
      - '${HOST_MAILHOG_DASHBOARD_PORT:-0}:8025'
